Support additional arguments for deprecated decorator (fix #2)
getslash/vintage pull request #6
Opened 2017-06-27 20:52 UTC by ayalash

Added arguments: message, since, what, frame_correction

2017-06-27 20:56 UTC, vmalloc requested changes

2017-06-27 20:56 UTC, vmalloc commented on vintage/__init__.py
> +        warn_deprecation(warning, frame_correction=self._frame_correction)
@ayalash shouldn't it be `self._frame_correction + 1`?

2017-06-27 21:36 UTC, ayalash commented on vintage/__init__.py
> +        warn_deprecation(warning, frame_correction=self._frame_correction)
@vmalloc Oops ... Sorry...
I pushed again with a fix and unittest for validate it.
Please review again.

2017-06-28 05:31 UTC, vmalloc approved these changes

2017-06-28 05:35 UTC, merged

2017-06-28 05:36 UTC, vmalloc commented
Thanks!